"""added refund, refundProduct assoc tables

Revision ID: 1257507ee9b5
Revises: 04b3514fbcbb
Create Date: 2021-08-13 14:28:55.079927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1257507ee9b5'
down_revision = '04b3514fbcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_orders_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_product_orders_association_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_orders_association_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name=op.f('pk_product_orders_association'))
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_table('product_refund_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_refund_association_product_id_products')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_product_refund_association_refund_id_refunds')),
    sa.PrimaryKeyConstraint('product_id', 'refund_id', name=op.f('pk_product_refund_association'))
    )
    op.drop_table('product_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_orders',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_product_orders_order_id_orders'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_orders_product_id_products'),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name='pk_product_orders')
    )
    op.drop_table('product_refund_association')
    op.drop_table('refunds')
    op.drop_table('product_orders_association')
    # ### end Alembic commands ###
