"""added date columns, enable flag for stores and products and a brand

Revision ID: 241aa36737ad
Revises: 8a00472c756b
Create Date: 2021-08-09 23:28:10.170404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241aa36737ad'
down_revision = '8a00472c756b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('customers', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('enable', sa.Boolean(), server_default='True', nullable=True))
    op.add_column('stores', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('stores', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('enable', sa.Boolean(), server_default='True', nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('stores', 'enable')
    op.drop_column('stores', 'updated_on')
    op.drop_column('stores', 'created_on')
    op.drop_column('products', 'enable')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'updated_on')
    op.drop_column('products', 'created_on')
    op.drop_column('orders', 'updated_on')
    op.drop_column('orders', 'created_on')
    op.drop_column('customers', 'updated_on')
    op.drop_column('customers', 'created_on')
    # ### end Alembic commands ###
