"""loose flag, ids change in product, store models from id -> pid, sid

Revision ID: 502379622afa
Revises: e4b480014ced
Create Date: 2021-09-17 09:57:31.650022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502379622afa'
down_revision = 'e4b480014ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # store id -> sid
    # op.add_column('stores', sa.Column('sid', sa.Integer(), nullable=False))

    # 1. Renaming primary column in stores
    op.drop_constraint('fk_store_product_store_id_stores', 'store_product', type_='foreignkey')
    op.drop_constraint('fk_orders_store_id_stores', 'orders', type_='foreignkey')

    # op.drop_constraint('pk_stores', 'stores', type_='primary')
    # op.drop_column('stores', 'id')
    # op.add_column('stores', sa.Column('sid', sa.INTEGER(), existing_server_default=sa.text("nextval('stores_id_seq'::regclass)"),
    #                                   autoincrement=True, nullable=False))

    op.alter_column('stores', 'id', new_column_name='sid')
    op.create_foreign_key(op.f('fk_orders_store_id_stores'), 'orders', 'stores', ['store_id'], ['sid'])
    op.create_foreign_key(op.f('fk_store_product_store_id_stores'), 'store_product', 'stores', ['store_id'], ['sid'])

    # 2. Renaming primary column in products
    op.drop_constraint('fk_store_product_product_id_products', 'store_product', type_='foreignkey')
    op.drop_constraint('fk_product_orders_association_product_id_products', 'product_orders_association', type_='foreignkey')
    op.drop_constraint('fk_product_refund_association_product_id_products', 'product_refund_association', type_='foreignkey')

    # op.drop_constraint('pk_products', 'products', type_='primary')
    # op.alter_column('products', 'id', new_column_name='pid', existing_server_default=sa.text("nextval('products_id_seq'::regclass)"),
    #                 autoincrement=True, nullable=False)
    op.alter_column('products', 'id', new_column_name='pid')

    op.create_foreign_key(op.f('fk_store_product_product_id_products'), 'store_product', 'products', ['product_id'],
                          ['pid'])
    op.create_foreign_key(op.f('fk_product_orders_association_product_id_products'), 'product_orders_association', 'products', ['product_id'], ['pid'])
    op.create_foreign_key(op.f('fk_product_refund_association_product_id_products'), 'product_refund_association', 'products', ['product_id'], ['pid'])

    # loose flag in products
    op.add_column('products', sa.Column('loose', sa.Boolean(), nullable=True))
    op.execute("UPDATE products SET loose = False")
    op.alter_column("products", "loose", nullable=False)

    # quantity from int -> float
    op.alter_column('products', 'quantity', type_=sa.Float, existing_type=sa.INTEGER)
    op.alter_column('product_orders_association', 'quantity', type_=sa.Float, existing_type=sa.INTEGER)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Revert: Renaming primary column in stores
    op.drop_constraint('fk_store_product_store_id_stores', 'store_product', type_='foreignkey')
    op.drop_constraint('fk_orders_store_id_stores', 'orders', type_='foreignkey')

    # op.drop_constraint('pk_stores', 'stores', type_='primary')
    # op.drop_column('stores', 'id')
    # op.add_column('stores', sa.Column('sid', sa.INTEGER(),
    #                existing_server_default=sa.text("nextval('stores_id_seq'::regclass)"),
    #                autoincrement=True, nullable=False)
    #                )

    op.alter_column('stores', 'sid', new_column_name='id')
    op.create_foreign_key(op.f('fk_orders_store_id_stores'), 'orders', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(op.f('fk_store_product_store_id_stores'), 'store_product', 'stores', ['store_id'], ['id'])
    # -------------
    # 2. Renaming primary column in products
    op.drop_constraint('fk_store_product_product_id_products', 'store_product', type_='foreignkey')
    op.drop_constraint('fk_product_orders_association_product_id_products', 'product_orders_association',
                       type_='foreignkey')
    op.drop_constraint('fk_product_refund_association_product_id_products', 'product_refund_association',
                       type_='foreignkey')

    # op.drop_constraint('pk_products', 'products', type_='primary')
    # op.alter_column('products', 'id', new_column_name='pid',
    #                  existing_server_default=sa.text("nextval('products_id_seq'::regclass)"),
    #                  autoincrement=True, nullable=False
    #                  )
    op.alter_column('products', 'pid', new_column_name='id')

    op.create_foreign_key(op.f('fk_store_product_product_id_products'), 'store_product', 'products', ['product_id'],
                          ['id'])
    op.create_foreign_key(op.f('fk_product_orders_association_product_id_products'), 'product_orders_association',
                          'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('fk_product_refund_association_product_id_products'), 'product_refund_association',
                          'products', ['product_id'], ['id'])
    # ------------------
    op.drop_column('products', 'loose')

    op.alter_column('products', 'quantity', type_=sa.INTEGER, existing_type=sa.Float)
    op.alter_column('product_orders_association', 'quantity', type_=sa.INTEGER, existing_type=sa.Float)

    # ### end Alembic commands ###


