"""adding store foreignkey in productModel

Revision ID: 6524f45d5a00
Revises: 502379622afa
Create Date: 2021-09-17 16:29:26.159655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524f45d5a00'
down_revision = '502379622afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sid', sa.Integer(), nullable=True))
    op.execute("UPDATE products SET sid = 1")
    op.create_foreign_key(op.f('fk_products_sid_stores'), 'products', 'stores', ['sid'], ['sid'])
    op.alter_column("products", "sid", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_sid_stores'), 'products', type_='foreignkey')
    op.drop_column('products', 'sid')
    # ### end Alembic commands ###
