"""on-delete-cascade in orders to  product_orders_assoc, customer to orders

Revision ID: 981b8a317583
Revises: c9d70c4d4fc1
Create Date: 2021-10-14 12:01:12.253659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981b8a317583'
down_revision = 'c9d70c4d4fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_customer_id_customers', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_customer_id_customers'), 'orders', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_orders_association_order_id_orders', 'product_orders_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_orders_association_order_id_orders'), 'product_orders_association', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_orders_association_order_id_orders'), 'product_orders_association', type_='foreignkey')
    op.create_foreign_key('fk_product_orders_association_order_id_orders', 'product_orders_association', 'orders', ['order_id'], ['id'])
    op.drop_constraint(op.f('fk_orders_customer_id_customers'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_customer_id_customers', 'orders', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
