"""added group column, for variants

Revision ID: 9ac6fdfc3edb
Revises: 6524f45d5a00
Create Date: 2021-09-24 15:01:57.334736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac6fdfc3edb'
down_revision = '6524f45d5a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('variant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'group')
    op.drop_column('products', 'variant_id')
    # ### end Alembic commands ###
