"""order_changes

Revision ID: c9d70c4d4fc1
Revises: 9ac6fdfc3edb
Create Date: 2021-10-06 16:56:48.478369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = 'c9d70c4d4fc1'
down_revision = '9ac6fdfc3edb'
branch_labels = None
depends_on = None

from models.secondary_tables import ProductOrdersAssociation
from models.product import ProductModel


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_orders_association', sa.Column('actual_price', sa.Float(), nullable=True))
    op.execute("UPDATE product_orders_association poa"
               " SET actual_price = p.actual_price"
               " FROM products p"
               " WHERE p.pid=poa.product_id")
    op.alter_column("product_orders_association", "actual_price", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_orders_association', 'actual_price')
    # ### end Alembic commands ###
